### PR TITLE
Improve error message on wrong type of mg.Deps argument (#240)

### PR DESCRIPTION
**Pull request by misha-tectonic**
This change adds a location of mg.Deps invocation, shrinking the search space
from "all your build scripts" to "this particular mg.Deps invocation"

### CODE REVIEW

**Comment by natefinch** [comment]
Looks good, but can you write a test for it?  Can be pretty simple, just something that'll break if we change the number of function calls between the name and the error?

**Comment by misha-tectonic** [comment]
Sure, added a test.

**Comment by natefinch** [comment]
hmm probably some problem on tip from go modules, I'll look into it.

**Comment by misha-tectonic** [comment]
Yes, I saw this test failing with modules.

**Pull request merged**
