### PR TITLE
Add `-ldflags` flag

### LINKED ISSUE #320: When compiling mage statically, cannot pass ldflags
## Thanks 

I'm one user who has used this project.
Thank you so much for always developing and maintaining compatibility!

## Requirement (business use case)

Add additional information to mage static binary via `-ldflags` .

For example, a use case for `-ldflags` would be if you want to verify that the mage binary is an up-to-date magefile.go binary.

By using `-ldflags` to embed the hash value in the mage binary, you can compare it with the latest magefile.go's hash to see if it is the latest one.

It's also useful to include Git information.

## Problem

Currently, when compiling mage statically, mage doesn't support `ldflags` flag.

## Proposal

Add a new flag `-ldflags` for mage.

This flag can be used in case of passed `-compile` flag.

I want to add this flag [around here](https://github.com/magefile/mage/blob/master/mage/main.go#L509).

## Remark

I have a patch for this issue.
So, i can send a PR.
Thanks!

### PR DESCRIPTION
**Pull request by tukeJonny**
Resolve #320 .

### CODE REVIEW

**Comment by tukeJonny** [comment]
I checked Twitter and it seems that there is an issue with travis not being able to start the build in some cases.
It seems to be due to the fact that the queue is not being processed, but I have no idea how long it will take to run.

In the meantime, the following tests have passed in my darwin(MacOS) environment.

```
$ go test -race ./...
?       github.com/magefile/mage        [no test files]
?       github.com/magefile/mage/internal       [no test files]
ok      github.com/magefile/mage/mage   31.190s
ok      github.com/magefile/mage/mg     0.800s
ok      github.com/magefile/mage/parse  1.196s
ok      github.com/magefile/mage/sh     0.949s
ok      github.com/magefile/mage/target 0.583s
```

**Comment by tukeJonny** [comment]
@natefinch 

Travis is running, but from what I've seen of [travis's builds](https://travis-ci.org/github/magefile/mage/builds/741314025),  the build seems to be a success.

**Comment by tukeJonny** [comment]
@natefinch 

Sorry for notifying you many times .

Let me know if there is anything that I can resolve that is hindering the review.

As a known issue, the Travis results are not being picked up by Github, but this seems to be more due to Travis than a code issue.

**Review by natefinch — APPROVED** [review]
This looks good. Thank you! I'll poke travis tonight just to double check the build, but then I can merge it.

**Comment by tukeJonny** [comment]
@natefinch 

Thank you!
Then, is it likely to be double check in Travis?

**Comment by natefinch** [comment]
Travis is kind of messed up right now... but this ran and passed, so I'll call it good.
https://travis-ci.com/github/magefile/mage/builds/202629089

**Pull request merged**
