### PR TITLE
Fix for Issue #122

### PR DESCRIPTION
**Pull request by bdalton**
Love magefile and will be using it for all my go projects going forward.

This started as my own target module when I couldn't get the bundled 'target' module to work the way I needed it to. I've expanded the unit tests also. Feel free to cherry-pick or alter anything.

Barnaby

### CODE REVIEW

**Comment by natefinch** [comment]
I've been looking at this off and on.  It's a bit bigger than I hoped, which is why I haven't gotten to it before now.  I'll try to get a handle on it soon.

**Comment by natefinch** [comment]
Oh man, I just started looking at the target stuff and whoo boy, it's broken.  Lemme look at your code.

**Comment by natefinch** [comment]
Clarification: the existing code is broken.... not yours :)

**Comment by natefinch** [comment]
#131 addresses this.  If there's something different you'd like to do, we can talk about that (it looks like you changed the behavior slightly)... but I think that would need to perhaps be a new function.

**Comment by bdalton** [comment]
The tests codified what I needed. I couldn't get that behavior even with extra checks with the old code.
If it passes those, then it works for me. I'm not attached to the code I wrote.

I'm in the middle of a release now, so am hesitant to upgrade something I don't need to. I'll update to your changes and stop using my patch after I get things out the door.

Thanks

**Comment by natefinch** [comment]
Cool, yeah, like I said, I added your tests temporarily to my branch, and
they passed.  I should have just left them in there, honestly (more tests
is better), but alas, hindsight.

Anyway, yes, I understand about releases, no worries.  I merged my PR in,
because I was pretty confident in it.   Thanks again for the contribution,
it definitely spurred me to look more at this, and I'm glad I did.

**Pull request closed without merging**
